version: '3'

services:

  database:
    container_name: yampacked-database
    build:
      context: ./backend
      dockerfile: ./db/Dockerfile
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust # TODO: remove this
      - POSTGRES_PASSWORD=password # TODO: paramaterise this
    networks:
      - database-network
    ports:
      - "5432:5432"

  api:
    container_name: yampacked-api
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=yampacked-database
      - DB_NAME=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - API_HOST=0.0.0.0
    volumes:
      - ./backend:/app
    networks:
      - database-network

  frontend:
    container_name: yampacked-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - api

networks:
  database-network:
