version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - api
      - frontend
    networks:
      - kaktus-network

  database:
    container_name: database
    build:
      context: ./backend
      dockerfile: ./db/Dockerfile
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust # TODO: remove this
      - POSTGRES_PASSWORD=password # TODO: paramaterise this
    networks:
      - kaktus-network
    ports:
      - "5432:5432"

  api:
    container_name: api
    depends_on:
      - database
    build:
      context: ./backend
      dockerfile: ./api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - API_HOST=0.0.0.0
    volumes:
      - ./backend:/app
    networks:
      - kaktus-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    networks:
      - kaktus-network

networks:
  kaktus-network:
